version: '3.8'

services:
  app:
    image: shedzo/bookhub
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=bookhub
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass1234
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: bookhub
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: